version: '3'

networks:
  microservices-net:
    driver: bridge

services:
  web:
    build: './web'
    restart: always
    command: npm start
    networks:
      - microservices-net
    volumes:
      - ./web:/usr/app

  user:
    build: './user'
    restart: always
    command: npm start
    networks:
      - microservices-net
    volumes:
      - ./user:/usr/app
    depends_on:
      - mongodb
    environment:
      - MONGO_DB_URI=mongodb://mongodb/microservices

  auth: 
    build: './auth'
    restart: always
    command: npm start
    networks:
      - microservices-net
    volumes:
      - ./auth:/usr/app
    environment:
      - KEY_ACCESS_TOKEN=key0987654321

  mongodb:
    image: mongo
    volumes:
      - ./mongodb:/data/db
    networks:
      - microservices-net

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - microservices-net
    depends_on:
      - web
      - user
      - auth