version: '3'

networks:
  microservices-net:
    driver: bridge

services:
  web:
    build: './web'
    restart: always
    # ports:
    #   - "3000:3000"
    networks:
      - microservices-net

  user:
    build: './user'
    restart: always
    # ports:
    #   - "3001:3000"
    networks:
      - microservices-net


  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - microservices-net
    depends_on:
      - web
      - user